[project]
name = "llm2ner"
version = "0.2.0"
description = "Codebase for using and training ToMMer models : Token Matching Entity Recognition"
readme = "README.md"
requires-python = ">=3.10,!=3.11"
dependencies = [
    "circuitsvis>=1.43.3",
    "einops>=0.8.1",
    "experimaestro",
    "ipywidgets>=8.1.6",
    "matplotlib",
    "notebook",
    "anywidget>=0.9.18",
    "openpyxl>=3.1.5",
    "plotly>=6.0.1",
    "scikit-learn",
    "spacy",
    "tensorboard>=2.20.0",
    "transformer-lens>=2.15.0",
]

[tool.uv]
package = true

[tool.uv.sources]
llm2ner = { workspace = true }
experimaestro = { git = "https://github.com/experimaestro/experimaestro-python", tag = "2.0.0a1" }

[tool.setuptools]
# ...
include-package-data = true

[tool.setuptools.package-data]
"llm2ner.models" = ["*.md"]

[tool.uv.workspace]
members = [
    ".",
]

[dependency-groups]
dev = [
    "llm2ner",
    "openai>=2.6.0",
    "rotary-embedding-torch>=0.8.9",
]
